// frontend/src/components/ServiceCard.tsx
import { type ReactElement, useMemo, useRef, useState } from "react";
import type { ServiceInstance } from "../../../common/stack.ts";
import { elementValue, useElementEvent } from "../lib/dom-events.ts";
import { useT } from "../lib/i18n.ts";
import { useSizeClass } from "../lib/media.ts";
import { linkHandler } from "../lib/router.ts";
import { parsePort } from "../pages/compose/sync.ts";
import NetworkInput from "../pages/compose/NetworkInput.tsx";
import ArrayInput from "./ArrayInput.tsx";
import BottomSheet from "./BottomSheet.tsx";
import ConfirmDialog from "./ConfirmDialog.tsx";
import "./ServiceCard.css";
import StatusChip from "./StatusChip.tsx";

interface ContainerStats {
    Name?: string;
    CPUPerc?: string;
    MemUsage?: string;
}

interface Props {
    name: string;
    stackName: string;
    service: Record<string, unknown> | undefined;
    editable: boolean;
    multiService: boolean;
    status?: ServiceInstance[];
    stats?: ContainerStats[];
    expandedPorts?: string[];
    availableNetworks: string[];
    onStart?: (name: string) => void;
    onStop?: (name: string) => void;
    onRestart?: (name: string) => void;
    onRemove: (name: string) => void;
    onServiceChange: (name: string, patch: Record<string, unknown>) => void;
}

function stringField(service: Record<string, unknown>, key: string): string | undefined {
    const value = service[key];
    return typeof value === "string" ? value : undefined;
}

function stringArrayField(service: Record<string, unknown>, key: string): string[] | undefined {
    const value = service[key];
    if (!Array.isArray(value)) return undefined;
    return value.filter((entry): entry is string => typeof entry === "string");
}

export default function ServiceCard({
    name,
    stackName,
    service,
    editable,
    multiService,
    status,
    stats,
    expandedPorts,
    availableNetworks,
    onStart,
    onStop,
    onRestart,
    onRemove,
    onServiceChange,
}: Props): ReactElement {
    const { t } = useT();
    const sizeClass = useSizeClass();

    const [removeConfirm, setRemoveConfirm] = useState(false);
    const [statsExpanded, setStatsExpanded] = useState(false);
    const [overflowOpen, setOverflowOpen] = useState(false);
    const imageRef = useRef<HTMLElement>(null);

    useElementEvent(imageRef, "input", () => onServiceChange(name, { image: elementValue(imageRef) }));

    // The backend's service status no longer reports per-instance shell availability (see
    // ServiceInstance in common/stack.ts); the closest available signal is that the service
    // has at least one known container instance. `terminal.exec` rejects a shell into a
    // service that is not actually running, so this only gates the affordance, not safety.
    const canShell = status !== undefined && status.length > 0;
    const primaryStatus = status?.[0]?.status ?? "unknown";
    const shellHref = `/terminal/${stackName}/${name}/sh`;

    const ports = useMemo(() => {
        const raw = expandedPorts ?? (service !== undefined ? stringArrayField(service, "ports") : undefined) ?? [];
        return raw.map((entry) => ({ entry, parsed: parsePort(entry, location.hostname) }));
    }, [expandedPorts, service]);

    const showInlineActions = !editable && sizeClass !== "compact";
    const showOverflowTrigger = !editable && sizeClass === "compact";

    return (
        <>
            <mdui-card variant="outlined">
                <div className="row">
                    <span className="type-title-medium">{name}</span>
                    {status !== undefined ? <StatusChip status={primaryStatus} /> : null}
                    <div className="row-end">
                        {showInlineActions ? (
                            <>
                                {canShell ? (
                                    <mdui-button variant="text" href={shellHref} onClick={linkHandler(shellHref)}>
                                        {t("service.action.shell")}
                                    </mdui-button>
                                ) : null}
                                {multiService ? (
                                    <>
                                        <mdui-button variant="text" onClick={() => onStart?.(name)}>
                                            {t("service.action.start")}
                                        </mdui-button>
                                        <mdui-button variant="text" onClick={() => onStop?.(name)}>
                                            {t("service.action.stop")}
                                        </mdui-button>
                                        <mdui-button variant="text" onClick={() => onRestart?.(name)}>
                                            {t("service.action.restart")}
                                        </mdui-button>
                                    </>
                                ) : null}
                            </>
                        ) : null}
                        {showOverflowTrigger ? (
                            <mdui-button-icon
                                icon="more_vert"
                                aria-label={t("action.more")}
                                onClick={() => setOverflowOpen(true)}
                            />
                        ) : null}
                    </div>
                </div>

                {!editable ? (
                    <dl className="service-details">
                        <dt className="type-label-medium text-muted">{t("stack.service.image")}</dt>
                        <dd className="mono type-body-medium">
                            {service !== undefined ? (stringField(service, "image") ?? "") : ""}
                        </dd>

                        {ports.length > 0 ? (
                            <>
                                <dt className="type-label-medium text-muted">{t("stack.service.ports")}</dt>
                                <dd>
                                    <div className="row">
                                        {ports.map(({ entry, parsed }) =>
                                            parsed !== null ? (
                                                <a
                                                    key={entry}
                                                    href={parsed.url}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="status-chip type-label-medium"
                                                >
                                                    {parsed.display}
                                                </a>
                                            ) : (
                                                <span key={entry} className="status-chip type-label-medium">
                                                    {entry}
                                                </span>
                                            ),
                                        )}
                                    </div>
                                </dd>
                            </>
                        ) : null}

                        {stats !== undefined && stats.length > 0 ? (
                            <>
                                <dt className="type-label-medium text-muted">{t("stack.service.stats")}</dt>
                                <dd>
                                    <div className="row">
                                        <span className="type-label-medium text-muted mono">
                                            {stats[0]?.CPUPerc ?? "-"} CPU
                                        </span>
                                        <span className="type-label-medium text-muted mono">
                                            {stats[0]?.MemUsage ?? "-"}
                                        </span>
                                        {stats.length > 1 ? (
                                            <mdui-button-icon
                                                icon={statsExpanded ? "expand_less" : "expand_more"}
                                                aria-label={t("action.more")}
                                                aria-expanded={statsExpanded}
                                                onClick={() => setStatsExpanded(!statsExpanded)}
                                            />
                                        ) : null}
                                    </div>
                                    {statsExpanded
                                        ? stats.slice(1).map((stat) => (
                                              <div key={stat.Name} className="row">
                                                  <span className="type-label-medium text-muted">{stat.Name}</span>
                                                  <span className="type-label-medium text-muted mono">
                                                      {stat.CPUPerc ?? "-"}
                                                  </span>
                                                  <span className="type-label-medium text-muted mono">
                                                      {stat.MemUsage ?? "-"}
                                                  </span>
                                              </div>
                                          ))
                                        : null}
                                </dd>
                            </>
                        ) : null}
                    </dl>
                ) : service !== undefined ? (
                    <div className="form-column">
                        <mdui-text-field
                            ref={imageRef}
                            variant="outlined"
                            label={t("stack.service.image")}
                            value={stringField(service, "image") ?? ""}
                        />
                        <ArrayInput
                            items={stringArrayField(service, "ports")}
                            onChange={(items) => onServiceChange(name, { ports: items })}
                            label={t("stack.service.ports")}
                            placeholder={t("stack.service.hostContainerPlaceholder")}
                        />
                        <ArrayInput
                            items={stringArrayField(service, "volumes")}
                            onChange={(items) => onServiceChange(name, { volumes: items })}
                            label={t("stack.service.volumes")}
                            placeholder={t("stack.service.hostContainerPlaceholder")}
                        />
                        <ArrayInput
                            items={stringArrayField(service, "depends_on")}
                            onChange={(items) => onServiceChange(name, { depends_on: items })}
                            label={t("stack.service.dependsOn")}
                        />
                        <NetworkInput
                            networks={stringArrayField(service, "networks")}
                            onChange={(items) => onServiceChange(name, { networks: items })}
                            available={availableNetworks}
                        />
                        <div className="form-actions">
                            <mdui-button
                                variant="filled"
                                className="danger-action"
                                onClick={() => setRemoveConfirm(true)}
                            >
                                {t("service.action.remove")}
                            </mdui-button>
                        </div>
                    </div>
                ) : null}
            </mdui-card>

            <BottomSheet open={overflowOpen} title={name} onClose={() => setOverflowOpen(false)}>
                <mdui-list>
                    {canShell ? (
                        <mdui-list-item
                            href={shellHref}
                            onClick={(event) => {
                                setOverflowOpen(false);
                                linkHandler(shellHref)(event);
                            }}
                        >
                            {t("service.action.shell")}
                        </mdui-list-item>
                    ) : null}
                    {multiService ? (
                        <>
                            <mdui-list-item
                                onClick={() => {
                                    setOverflowOpen(false);
                                    onStart?.(name);
                                }}
                            >
                                {t("service.action.start")}
                            </mdui-list-item>
                            <mdui-list-item
                                onClick={() => {
                                    setOverflowOpen(false);
                                    onStop?.(name);
                                }}
                            >
                                {t("service.action.stop")}
                            </mdui-list-item>
                            <mdui-list-item
                                onClick={() => {
                                    setOverflowOpen(false);
                                    onRestart?.(name);
                                }}
                            >
                                {t("service.action.restart")}
                            </mdui-list-item>
                        </>
                    ) : null}
                </mdui-list>
            </BottomSheet>

            <ConfirmDialog
                open={removeConfirm}
                title={t("service.action.remove")}
                message={name}
                danger
                onConfirm={() => {
                    setRemoveConfirm(false);
                    onRemove(name);
                }}
                onCancel={() => setRemoveConfirm(false)}
            />
        </>
    );
}

// frontend/src/components/ServiceCard.svelte
<script lang="ts">
    import { MediaQuery } from "svelte/reactivity";
    import { t } from "../lib/stores/i18n.svelte.ts";
    import ArrayInput from "./ArrayInput.svelte";
    import ConfirmDialog from "./ConfirmDialog.svelte";
    import MenuButton, { type MenuItemSpec } from "./MenuButton.svelte";
    import StatusChip from "./StatusChip.svelte";
    import NetworkInput from "../pages/compose/NetworkInput.svelte";
    import { parsePort } from "../pages/compose/sync.ts";

    interface Props {
        name: string;
        service: {
            image?: string;
            ports?: string[];
            volumes?: string[];
            depends_on?: string[];
            networks?: string[];
        };
        editable: boolean;
        multiService: boolean;
        status?: Array<{ state?: string; health?: string; status?: string; shellAvailable?: boolean }>;
        stats?: Array<{ Name: string; CPUPerc?: string; MemUsage?: string }>;
        expandedPorts?: string[];
        availableNetworks: string[];
        onstart?: (name: string) => void;
        onstop?: (name: string) => void;
        onrestart?: (name: string) => void;
        onremove?: (name: string) => void;
    }

    let {
        name,
        service,
        editable,
        multiService,
        status,
        stats,
        expandedPorts,
        availableNetworks,
        onstart,
        onstop,
        onrestart,
        onremove,
    }: Props = $props();

    const isMedium = new MediaQuery("width >= 600px");

    let removeConfirm = $state(false);
    let statsExpanded = $state(false);

    const primaryStatus = $derived.by(() => {
        if (status === undefined || status.length === 0) return "unknown";
        const first = status[0];
        if (first === undefined) return "unknown";
        return first.health || first.state || first.status || "unknown";
    });

    const canShell = $derived(status?.some((s) => s.shellAvailable === true) ?? false);

    const ports = $derived.by(() => {
        const raw = expandedPorts ?? service?.ports ?? [];
        return raw.map((entry) => {
            const parsed = parsePort(entry, location.hostname);
            return { entry, parsed };
        });
    });

    const menuItems = $derived.by((): MenuItemSpec[] => {
        const items: MenuItemSpec[] = [];
        if (canShell) {
            items.push({
                label: t("service.action.shell"),
                onSelect: () => {
                    location.href = `/terminal/${name}/service/sh`;
                },
            });
        }
        if (multiService) {
            items.push(
                { label: t("service.action.start"), onSelect: () => onstart?.(name) },
                { label: t("service.action.stop"), onSelect: () => onstop?.(name) },
                { label: t("service.action.restart"), onSelect: () => onrestart?.(name) },
            );
        }
        return items;
    });

    function setImage(val: string): void {
        if (service !== undefined) {
            service.image = val;
        }
    }
</script>

<div class="gcp-service-card" data-audit-id="service-card-{name}" data-audit-column>
    <div class="gcp-service-header" data-audit-row="center">
        <span class="text-title gcp-service-name" data-audit-clip>{name}</span>
        {#if status !== undefined}
            <StatusChip status={primaryStatus} />
        {/if}
        <div class="gcp-service-spacer"></div>

        {#if !editable}
            {#if isMedium.current}
                {#if canShell}
                    <a class="gcp-service-btn" href="/terminal/{name}/service/sh">{t("service.action.shell")}</a>
                {/if}
                {#if multiService}
                    <button type="button" class="gcp-service-btn" onclick={() => onstart?.(name)}>
                        {t("service.action.start")}
                    </button>
                    <button type="button" class="gcp-service-btn" onclick={() => onstop?.(name)}>
                        {t("service.action.stop")}
                    </button>
                    <button type="button" class="gcp-service-btn" onclick={() => onrestart?.(name)}>
                        {t("service.action.restart")}
                    </button>
                {/if}
            {:else}
                <MenuButton items={menuItems} />
            {/if}
        {/if}
    </div>

    {#if !editable}
        <div class="gcp-service-body" data-audit-column>
            <span class="text-body-medium gcp-service-image">{service?.image ?? ""}</span>

            {#if ports.length > 0}
                <div class="gcp-service-ports">
                    {#each ports as { entry, parsed } (entry)}
                        {#if parsed !== null}
                            <a class="gcp-port-chip" href={parsed.url} target="_blank" rel="noopener noreferrer">
                                {parsed.display}
                            </a>
                        {:else}
                            <span class="gcp-port-chip">{entry}</span>
                        {/if}
                    {/each}
                </div>
            {/if}

            {#if stats !== undefined && stats.length > 0}
                <div class="gcp-service-stats" data-audit-row="center">
                    <span class="gcp-stat-item text-label">{stats[0]?.CPUPerc ?? "-"} CPU</span>
                    <span class="gcp-stat-item text-label">{stats[0]?.MemUsage ?? "-"}</span>
                    {#if stats.length > 1}
                        <button
                            type="button"
                            class="gcp-stats-expander"
                            aria-expanded={statsExpanded}
                            onclick={() => (statsExpanded = !statsExpanded)}
                        >
                            {statsExpanded ? "−" : "+"}
                        </button>
                    {/if}
                </div>
                {#if statsExpanded}
                    {#each stats.slice(1) as stat (stat.Name)}
                        <div class="gcp-service-stats" data-audit-row="center">
                            <span class="gcp-stat-item text-label">{stat.Name}</span>
                            <span class="gcp-stat-item text-label" data-audit-numeric>{stat.CPUPerc ?? "-"}</span>
                            <span class="gcp-stat-item text-label" data-audit-numeric>{stat.MemUsage ?? "-"}</span>
                        </div>
                    {/each}
                {/if}
            {/if}
        </div>
    {:else if service !== undefined}
        <div class="gcp-service-edit" data-audit-column>
            <label class="gcp-service-field" data-audit-heading>
                <span class="text-label">Image</span>
                <input
                    type="text"
                    class="gcp-service-input"
                    value={service.image ?? ""}
                    oninput={(e) => setImage(e.currentTarget.value)}
                />
            </label>
            <ArrayInput bind:items={service.ports} label="Ports" placeholder="HOST:CONTAINER" />
            <ArrayInput bind:items={service.volumes} label="Volumes" placeholder="HOST:CONTAINER" />
            <ArrayInput bind:items={service.depends_on} label="Depends on" />
            <NetworkInput bind:networks={service.networks} available={availableNetworks} />
            <button type="button" class="gcp-service-remove-btn" onclick={() => (removeConfirm = true)}>
                {t("service.action.remove")}
            </button>
        </div>
    {/if}
</div>

<ConfirmDialog
    open={removeConfirm}
    title={t("service.action.remove")}
    message={name}
    danger
    onconfirm={() => {
        removeConfirm = false;
        onremove?.(name);
    }}
    oncancel={() => (removeConfirm = false)}
/>

<style>
    .gcp-service-card {
        display: flex;
        flex-direction: column;
        padding: var(--space-4);
        border-radius: var(--radius-md);
        box-shadow: inset 0 0 0 1px var(--m3c-outline-variant);
        background: var(--m3c-surface-container-low);
        gap: var(--space-3);
    }

    .gcp-service-header {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        gap: var(--space-2);
        min-height: var(--size-control-md);
    }

    .gcp-service-name {
        overflow: hidden;
        flex-shrink: 1;
        min-width: 0;
        text-overflow: ellipsis;
        white-space: nowrap;
        font-weight: 600;
    }

    .gcp-service-spacer {
        flex: 1;
        min-width: 0;
    }

    .gcp-service-btn {
        display: inline-flex;
        align-items: center;
        flex-shrink: 0;
        block-size: var(--size-control-sm);
        padding-block: 0;
        padding-inline: var(--space-3);
        border: 1px solid var(--m3c-outline-variant);
        border-radius: var(--radius-xs);
        background: var(--m3c-surface-container-high);
        color: var(--m3c-on-surface);
        cursor: pointer;
        text-decoration: none;
        white-space: nowrap;
        font-size: 12px;
        font-weight: 500;
    }

    .gcp-service-btn:hover {
        background: var(--m3c-surface-container-highest);
    }

    @media (pointer: coarse) {
        .gcp-service-btn {
            block-size: var(--size-control-lg);
        }
    }

    .gcp-service-body {
        display: flex;
        flex-direction: column;
        min-width: 0;
        gap: var(--space-2);
    }

    .gcp-service-image {
        font-family: "JetBrains Mono", monospace;
        font-size: 12px;
        color: var(--m3c-on-surface-variant);
        overflow-wrap: anywhere;
    }

    .gcp-service-ports {
        display: flex;
        flex-wrap: wrap;
        gap: var(--space-2);
    }

    .gcp-port-chip {
        display: inline-flex;
        align-items: center;
        min-height: var(--size-control-sm);
        padding-block: var(--space-2);
        padding-inline: var(--space-3);
        border-radius: var(--radius-xl);
        background: var(--m3c-secondary-container);
        color: var(--m3c-on-secondary-container);
        text-decoration: none;
        line-height: var(--space-4);
        font-size: 12px;
    }

    @media (pointer: coarse) {
        .gcp-port-chip {
            min-height: var(--size-control-lg);
        }
    }

    .gcp-service-stats {
        display: flex;
        align-items: center;
        gap: var(--space-3);
    }

    .gcp-stat-item {
        color: var(--m3c-on-surface-variant);
        font-variant-numeric: tabular-nums;
    }

    .gcp-stats-expander {
        width: var(--size-icon-lg);
        height: var(--size-icon-lg);
        border: none;
        background: transparent;
        color: var(--m3c-primary);
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
    }

    .gcp-service-edit {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
    }

    .gcp-service-field {
        display: flex;
        flex-direction: column;
        gap: var(--space-1);
    }

    .gcp-service-input {
        min-width: 0;
        block-size: var(--size-control-md);
        padding-block: 0;
        padding-inline: var(--space-3);
        border: 1px solid var(--m3c-outline-variant);
        background: var(--m3c-surface-container-lowest);
        color: var(--m3c-on-surface);
        font-family: inherit;
    }

    .gcp-service-remove-btn {
        align-self: flex-start;
        block-size: var(--size-control-md);
        padding-block: 0;
        padding-inline: var(--space-3);
        border: none;
        border-radius: var(--radius-xs);
        background: var(--m3c-error);
        color: var(--m3c-on-error);
        font-weight: 500;
        font-size: 13px;
        cursor: pointer;
    }
</style>
