// frontend/src/components/StatusChip.svelte
<script lang="ts">
    import Badge from "./Badge.svelte";
    import { CREATED, DRAFT, EXITED, RUNNING, statusKey, type StackStatus } from "$common/stack.ts";
    import { t } from "../lib/stores/i18n.svelte.ts";

    /**
     * Status is never conveyed by colour alone: the chip always carries the word. `tone` is
     * derived from either a stack status number or a per-service status string.
     */
    interface Props {
        status?: StackStatus;
        service?: string;
        auditId?: string;
    }

    const { status, service, auditId }: Props = $props();

    type Tone = "good" | "bad" | "wait" | "neutral" | "draft";

    const SERVICE_TONE: Record<string, Tone> = {
        running: "good",
        healthy: "good",
        unhealthy: "bad",
        starting: "wait",
        restarting: "wait",
        created: "neutral",
        paused: "neutral",
        exited: "bad",
        dead: "bad",
    };

    const tone = $derived.by((): Tone => {
        if (service !== undefined) return SERVICE_TONE[service.toLowerCase()] ?? "neutral";
        switch (status) {
            case RUNNING:
                return "good";
            case EXITED:
                return "bad";
            case CREATED:
                return "neutral";
            case DRAFT:
                return "draft";
            default:
                return "neutral";
        }
    });

    const label = $derived.by(() => {
        if (service !== undefined) {
            const key = `service${service.charAt(0).toUpperCase()}${service.slice(1).toLowerCase()}`;
            const translated = t(key);
            return translated === key ? service : translated;
        }
        return t(statusKey(status ?? 0));
    });
</script>

<Badge {tone} dot auditId={auditId ?? "status-chip"}>{label}</Badge>

// frontend/src/components/StatusChip.tsx
import type { ReactElement } from "react";
import { useT } from "../lib/i18n.ts";

type Tone = "running" | "error" | "pending" | "info" | "neutral";

const TONE_BY_STATUS: Record<string, Tone> = {
    running: "running",
    healthy: "running",
    exited: "error",
    dead: "error",
    unhealthy: "error",
    restarting: "pending",
    starting: "pending",
    paused: "pending",
    created: "info",
    draft: "info",
};

const LABEL_KEY_BY_STATUS: Record<string, string> = {
    running: "stack.status.running",
    exited: "stack.status.exited",
    created: "stack.status.created",
    draft: "stack.status.draft",
    unknown: "stack.status.unknown",
    healthy: "stack.status.healthy",
    unhealthy: "stack.status.unhealthy",
    starting: "stack.status.starting",
    restarting: "stack.status.restarting",
    paused: "stack.status.paused",
    dead: "stack.status.dead",
};

export default function StatusChip({ status }: { status: string }): ReactElement {
    const { t } = useT();
    const normalized = status.toLowerCase();
    const tone = TONE_BY_STATUS[normalized] ?? "neutral";
    const labelKey = LABEL_KEY_BY_STATUS[normalized];
    // An unmapped state is docker's own word, which beats showing nothing.
    const label = labelKey !== undefined ? t(labelKey) : status || t("stack.status.unknown");

    return (
        <span
            className={`status-chip type-label-medium${tone === "neutral" ? "" : ` status-chip--${tone}`}`}
        >
            <span className="status-chip__dot" aria-hidden="true" />
            {label}
        </span>
    );
}
