// frontend/src/pages/Dashboard.tsx
import { useMutation } from "@tanstack/react-query";
import {
    type CSSProperties,
    type FormEvent,
    type ReactElement,
    type ReactNode,
    type RefObject,
    useMemo,
    useRef,
    useState,
} from "react";
import { EXITED, RUNNING } from "../../../common/stack.ts";
import ConfirmDialog from "../components/ConfirmDialog.tsx";
import RowActions from "../components/RowActions.tsx";
import BottomSheet from "../components/BottomSheet.tsx";
import { elementValue, setElementValue, useElementEvent } from "../lib/dom-events.ts";
import { useT } from "../lib/i18n.ts";
import { useSizeClass } from "../lib/media.ts";
import { type AgentStatusValue, agents, stacks } from "../lib/push.ts";
import { navigate } from "../lib/router.ts";
import { useStore } from "../lib/store.ts";
import { request } from "../lib/transport.ts";
import "./Dashboard.css";

const HOST_DOT_COLOR: Record<AgentStatusValue, string> = {
    online: "rgb(var(--mdui-color-success))",
    offline: "rgb(var(--mdui-color-error))",
    unreachable: "rgb(var(--mdui-color-outline))",
    connecting: "rgb(var(--mdui-color-outline))",
};

interface DotStyle extends CSSProperties {
    "--host-dot-color": string;
}

function dotStyle(color: string): DotStyle {
    return { "--host-dot-color": color };
}

function errorText(error: Error | null, fallback: string): string | null {
    if (error === null) return null;
    return error.message !== "" ? error.message : fallback;
}

interface AddHostFields {
    urlRef: RefObject<HTMLElement | null>;
    usernameRef: RefObject<HTMLElement | null>;
    passwordRef: RefObject<HTMLElement | null>;
    nameRef: RefObject<HTMLElement | null>;
    url: string;
    error: string | null;
    pending: boolean;
    onSubmit: (event: FormEvent<HTMLFormElement>) => void;
}

function AddHostForm({
    urlRef,
    usernameRef,
    passwordRef,
    nameRef,
    url,
    error,
    pending,
    onSubmit,
}: AddHostFields): ReactElement {
    const { t } = useT();
    return (
        <form className="form-column" onSubmit={onSubmit}>
            {error !== null ? (
                <span className="type-label-medium danger-text" role="alert">
                    {error}
                </span>
            ) : null}
            <mdui-text-field ref={urlRef} variant="outlined" label={t("host.url")} required />
            <mdui-text-field ref={usernameRef} variant="outlined" label={t("host.username")} required />
            <mdui-text-field
                ref={passwordRef}
                variant="outlined"
                type="password"
                toggle-password
                label={t("host.password")}
            />
            <mdui-text-field ref={nameRef} variant="outlined" label={t("host.name")} />
            <mdui-button type="submit" variant="filled" disabled={pending || url.trim() === ""}>
                {t("dashboard.hosts.add")}
            </mdui-button>
        </form>
    );
}

export default function Dashboard(): ReactElement {
    const { t } = useT();
    const sizeClass = useSizeClass();
    const { byKey } = useStore(stacks);
    const { byEndpoint, statuses } = useStore(agents);

    const counts = useMemo(() => {
        let active = 0;
        let exited = 0;
        let inactive = 0;
        for (const summary of Object.values(byKey)) {
            if (summary.status === RUNNING) active++;
            else if (summary.status === EXITED) exited++;
            else inactive++;
        }
        return { active, exited, inactive };
    }, [byKey]);

    // Composerize converter
    const [dockerRunCommand, setDockerRunCommand] = useState("");
    const commandRef = useRef<HTMLElement>(null);
    useElementEvent(commandRef, "input", () => setDockerRunCommand(elementValue(commandRef)));

    const convertMutation = useMutation({
        mutationFn: (command: string) =>
            request<{ composeYAML?: string }>("", "docker.composerize", { command }),
    });
    const converterError = errorText(convertMutation.error, t("error.invalidCompose"));

    async function handleConvert(event: FormEvent<HTMLFormElement>): Promise<void> {
        event.preventDefault();
        const cmd = dockerRunCommand.trim();
        if (cmd === "" || convertMutation.isPending) return;
        try {
            const res = await convertMutation.mutateAsync(cmd);
            if (res.composeYAML !== undefined) {
                sessionStorage.setItem("docknight-compose-draft", res.composeYAML);
                await navigate("/compose");
            }
        } catch {
            // surfaced via convertMutation.error above
        }
    }

    // Host management
    const addUrlRef = useRef<HTMLElement>(null);
    const addUsernameRef = useRef<HTMLElement>(null);
    const addPasswordRef = useRef<HTMLElement>(null);
    const addNameRef = useRef<HTMLElement>(null);
    const [addUrl, setAddUrl] = useState("");
    const [addSheetOpen, setAddSheetOpen] = useState(false);
    useElementEvent(addUrlRef, "input", () => setAddUrl(elementValue(addUrlRef)));

    const addHostMutation = useMutation({
        mutationFn: (vars: { url: string; username: string; password: string; name?: string }) =>
            request("", "agent.add", vars),
    });
    const addHostError = errorText(addHostMutation.error, t("error.agentUnreachable"));

    const [removeTargetUrl, setRemoveTargetUrl] = useState<string | null>(null);
    const [renameTargetEndpoint, setRenameTargetEndpoint] = useState<string | null>(null);
    const [renameNewName, setRenameNewName] = useState("");
    const renameNameRef = useRef<HTMLElement>(null);
    useElementEvent(renameNameRef, "input", () => setRenameNewName(elementValue(renameNameRef)));

    const removeHostMutation = useMutation({
        mutationFn: (url: string) => request("", "agent.remove", { url }),
    });
    const renameHostMutation = useMutation({
        mutationFn: (vars: { endpoint: string; name: string }) => request("", "agent.rename", vars),
    });

    async function handleAddHost(event: FormEvent<HTMLFormElement>): Promise<void> {
        event.preventDefault();
        const url = addUrl.trim();
        if (url === "" || addHostMutation.isPending) return;
        const username = elementValue(addUsernameRef).trim();
        const password = elementValue(addPasswordRef);
        const name = elementValue(addNameRef).trim();
        try {
            await addHostMutation.mutateAsync({ url, username, password, name: name || undefined });
            setAddUrl("");
            setElementValue(addUrlRef, "");
            setElementValue(addUsernameRef, "");
            setElementValue(addPasswordRef, "");
            setElementValue(addNameRef, "");
            setAddSheetOpen(false);
        } catch {
            // surfaced via addHostMutation.error above
        }
    }

    async function confirmRemoveHost(): Promise<void> {
        if (removeTargetUrl === null) return;
        const target = removeTargetUrl;
        setRemoveTargetUrl(null);
        try {
            await removeHostMutation.mutateAsync(target);
        } catch {
            // The old dashboard did not surface remove failures either.
        }
    }

    async function confirmRenameHost(): Promise<void> {
        if (renameTargetEndpoint === null) return;
        const endpoint = renameTargetEndpoint;
        const name = renameNewName.trim();
        setRenameTargetEndpoint(null);
        try {
            await renameHostMutation.mutateAsync({ endpoint, name });
        } catch {
            // The old dashboard did not surface rename failures either.
        }
    }

    const remoteAgents = Object.values(byEndpoint).filter((agent) => agent.endpoint !== "");

    const addHostForm: ReactNode = (
        <AddHostForm
            urlRef={addUrlRef}
            usernameRef={addUsernameRef}
            passwordRef={addPasswordRef}
            nameRef={addNameRef}
            url={addUrl}
            error={addHostError}
            pending={addHostMutation.isPending}
            onSubmit={(event) => void handleAddHost(event)}
        />
    );

    return (
        <div className="page dashboard-page">
            <div className="page-header">
                <h1 className="type-headline-small">{t("dashboard.title")}</h1>
            </div>

            <mdui-card variant="filled" className="dashboard-overview">
                <div className="card-title">
                    <h2 className="type-title-medium">{t("dashboard.stacks.title")}</h2>
                </div>
                <div className="dashboard-metrics">
                    <div className="metric-card metric-card--active">
                        <div className="metric-card__label type-label-medium">
                            <mdui-icon name="play_circle--outlined" aria-hidden="true" />
                            <span>{t("dashboard.stacks.active")}</span>
                        </div>
                        <strong className="metric-card__value type-display-small">{counts.active}</strong>
                    </div>
                    <div className="metric-card metric-card--exited">
                        <div className="metric-card__label type-label-medium">
                            <mdui-icon name="error--outlined" aria-hidden="true" />
                            <span>{t("dashboard.stacks.exited")}</span>
                        </div>
                        <strong className="metric-card__value type-display-small">{counts.exited}</strong>
                    </div>
                    <div className="metric-card metric-card--inactive">
                        <div className="metric-card__label type-label-medium">
                            <mdui-icon name="pause_circle--outlined" aria-hidden="true" />
                            <span>{t("dashboard.stacks.inactive")}</span>
                        </div>
                        <strong className="metric-card__value type-display-small">{counts.inactive}</strong>
                    </div>
                </div>
            </mdui-card>

            <mdui-card variant="filled" className="dashboard-converter">
                <div className="card-title">
                    <h2 className="type-title-medium">{t("dashboard.converter.title")}</h2>
                </div>
                <form className="form-column" onSubmit={(event) => void handleConvert(event)}>
                    <mdui-text-field
                        ref={commandRef}
                        variant="outlined"
                        rows={3}
                        autosize
                        className="mono"
                        placeholder={t("dashboard.converter.placeholder")}
                        label={t("dashboard.converter.title")}
                    />
                    {converterError !== null ? (
                        <span className="type-label-medium danger-text" role="alert">
                            {converterError}
                        </span>
                    ) : null}
                    <div className="form-actions form-actions--end">
                        <mdui-button
                            type="submit"
                            variant="filled"
                            disabled={convertMutation.isPending || dockerRunCommand.trim() === ""}
                        >
                            {t("dashboard.converter.submit")}
                        </mdui-button>
                    </div>
                </form>
            </mdui-card>

            <mdui-card variant="filled" className="dashboard-hosts">
                <div className="card-title">
                    <h2 className="type-title-medium">{t("dashboard.hosts.title")}</h2>
                </div>

                <mdui-list>
                    <mdui-list-item headline={`${t("nav.home")} (Local)`} rounded nonclickable>
                        <span
                            slot="icon"
                            className="host-dot"
                            style={dotStyle(HOST_DOT_COLOR.online)}
                            aria-hidden="true"
                        />
                    </mdui-list-item>

                    {remoteAgents.map((agent) => {
                        const status = statuses[agent.endpoint]?.status ?? "connecting";
                        const displayName = agent.name !== undefined && agent.name !== "" ? agent.name : agent.endpoint;
                        return (
                            <mdui-list-item
                                key={agent.endpoint}
                                headline={displayName}
                                description={agent.url}
                                rounded
                                nonclickable
                            >
                                <span
                                    slot="icon"
                                    className="host-dot"
                                    style={dotStyle(HOST_DOT_COLOR[status])}
                                    aria-hidden="true"
                                />
                                <div slot="end-icon">
                                    <RowActions
                                        title={displayName}
                                        actions={[
                                            {
                                                label: t("dashboard.hosts.rename"),
                                                icon: "edit--outlined",
                                                onSelect: () => {
                                                    setRenameTargetEndpoint(agent.endpoint);
                                                    const initial = agent.name ?? "";
                                                    setRenameNewName(initial);
                                                    setElementValue(renameNameRef, initial);
                                                },
                                            },
                                            {
                                                label: t("dashboard.hosts.remove"),
                                                icon: "delete--outlined",
                                                danger: true,
                                                onSelect: () => setRemoveTargetUrl(agent.url),
                                            },
                                        ]}
                                    />
                                </div>
                            </mdui-list-item>
                        );
                    })}
                </mdui-list>

                {sizeClass === "compact" ? (
                    <>
                        <mdui-button
                            variant="tonal"
                            icon="add"
                            onClick={() => setAddSheetOpen(true)}
                        >
                            {t("dashboard.hosts.add")}
                        </mdui-button>
                        <BottomSheet
                            open={addSheetOpen}
                            title={t("dashboard.hosts.add")}
                            onClose={() => setAddSheetOpen(false)}
                        >
                            {addHostForm}
                        </BottomSheet>
                    </>
                ) : (
                    <>
                        <mdui-divider />
                        <div className="card-title">
                            <span className="type-title-medium">{t("dashboard.hosts.add")}</span>
                        </div>
                        {addHostForm}
                    </>
                )}
            </mdui-card>

            <ConfirmDialog
                open={removeTargetUrl !== null}
                title={t("dashboard.hosts.remove")}
                message={t("dashboard.hosts.removeConfirm", { url: removeTargetUrl ?? "" })}
                danger
                onConfirm={() => void confirmRemoveHost()}
                onCancel={() => setRemoveTargetUrl(null)}
            />

            <ConfirmDialog
                open={renameTargetEndpoint !== null}
                title={t("dashboard.hosts.rename")}
                confirmLabel={t("action.save")}
                onConfirm={() => void confirmRenameHost()}
                onCancel={() => setRenameTargetEndpoint(null)}
            >
                <mdui-text-field ref={renameNameRef} variant="outlined" label={t("host.name")} />
            </ConfirmDialog>
        </div>
    );
}

// frontend/src/pages/Dashboard.svelte
<script lang="ts">
    import { MediaQuery } from "svelte/reactivity";
    import { request } from "../lib/connection.svelte.ts";
    import { t } from "../lib/stores/i18n.svelte.ts";
    import { agents } from "../lib/stores/agents.svelte.ts";
    import { stacks } from "../lib/stores/stacks.svelte.ts";
    import { toastError } from "../lib/stores/toast.svelte.ts";
    import { navigate } from "../router.svelte.ts";
    import { RUNNING, EXITED } from "../../../common/stack.ts";
    import StackList from "../components/StackList.svelte";
    import ConfirmDialog from "../components/ConfirmDialog.svelte";
    import MenuButton from "../components/MenuButton.svelte";

    const isExpanded = new MediaQuery("width >= 840px");

    const counts = $derived.by(() => {
        let active = 0;
        let exited = 0;
        let inactive = 0;
        for (const summary of Object.values(stacks.byKey)) {
            if (summary.status === RUNNING) active += 1;
            else if (summary.status === EXITED) exited += 1;
            else inactive += 1;
        }
        return { active, exited, inactive };
    });

    let command = $state("");
    let convertError = $state<string | null>(null);
    let converting = $state(false);

    async function convert(): Promise<void> {
        convertError = null;
        converting = true;
        try {
            const result = await request("", "docker.composerize", { command });
            sessionStorage.setItem("docknight-compose-draft", result.yaml);
            await navigate("/compose");
        } catch (error) {
            convertError = error instanceof Error ? error.message : String(error);
        } finally {
            converting = false;
        }
    }

    let addUrl = $state("");
    let addUsername = $state("admin");
    let addPassword = $state("");
    let addName = $state("");
    let addError = $state<string | null>(null);
    let adding = $state(false);

    async function addHost(event: SubmitEvent): Promise<void> {
        event.preventDefault();
        addError = null;
        adding = true;
        try {
            await request("", "agent.add", {
                url: addUrl,
                username: addUsername,
                password: addPassword,
                name: addName === "" ? undefined : addName,
            });
            addUrl = "";
            addPassword = "";
            addName = "";
        } catch (error) {
            addError = error instanceof Error ? error.message : String(error);
        } finally {
            adding = false;
        }
    }

    let removeTarget = $state<string | null>(null);

    async function confirmRemove(): Promise<void> {
        if (removeTarget === null) return;
        try {
            await request("", "agent.remove", { url: removeTarget });
        } catch (error) {
            toastError(error);
        } finally {
            removeTarget = null;
        }
    }

    async function renameHost(url: string): Promise<void> {
        const current = agents.byEndpoint[Object.keys(agents.byEndpoint).find((e) => agents.byEndpoint[e]?.url === url) ?? ""];
        const next = prompt(t("dashboard.hosts.rename"), current?.name ?? "");
        if (next === null) return;
        try {
            await request("", "agent.rename", { url, name: next });
        } catch (error) {
            toastError(error);
        }
    }
</script>

<div class="dashboard" data-audit-root data-grid-origin>
    <div class="header-row" data-audit-row="center">
        <h1 class="text-headline">{t("dashboard.title")}</h1>
    </div>

    {#if !isExpanded.current}
        <div class="card" data-grid-origin>
            <StackList filter="" />
        </div>
    {/if}

    <div class="card counts" data-audit-row="center" data-grid-origin>
        <a class="count count-active" href="/?filter=running" onclick={(e) => e.preventDefault()}>
            <span class="count-dot active-dot" aria-hidden="true"></span>
            <span class="count-value text-headline" data-audit-numeric>{counts.active}</span>
            <span class="count-label text-label">{t("dashboard.stacks.active")}</span>
        </a>
        <a class="count count-exited" href="/?filter=exited" onclick={(e) => e.preventDefault()}>
            <span class="count-dot exited-dot" aria-hidden="true"></span>
            <span class="count-value text-headline" data-audit-numeric>{counts.exited}</span>
            <span class="count-label text-label">{t("dashboard.stacks.exited")}</span>
        </a>
        <a class="count count-inactive" href="/?filter=inactive" onclick={(e) => e.preventDefault()}>
            <span class="count-dot inactive-dot" aria-hidden="true"></span>
            <span class="count-value text-headline" data-audit-numeric>{counts.inactive}</span>
            <span class="count-label text-label">{t("dashboard.stacks.inactive")}</span>
        </a>
    </div>

    <div class="grid">
        <div class="card" data-audit-column data-grid-origin>
            <div class="card-title-row" data-audit-row="center">
                <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-audit-opaque>
                    <polyline points="4 17 10 11 4 5"/>
                    <line x1="12" y1="19" x2="20" y2="19"/>
                </svg>
                <h2 class="text-title">{t("dashboard.converter.title")}</h2>
            </div>
            <textarea
                class="command"
                placeholder={t("dashboard.converter.placeholder")}
                bind:value={command}
            ></textarea>
            {#if convertError !== null}
                <p class="error text-label">{convertError}</p>
            {/if}
            <button type="button" class="primary" disabled={converting || command.trim() === ""} onclick={convert}>
                {t("dashboard.converter.submit")}
            </button>
        </div>

        <div class="card" data-grid-origin>
            <div class="card-title-row" data-audit-row="center">
                <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-audit-opaque>
                    <rect x="2" y="2" width="20" height="8" rx="2" ry="2"/>
                    <rect x="2" y="14" width="20" height="8" rx="2" ry="2"/>
                    <line x1="6" y1="6" x2="6.01" y2="6"/>
                    <line x1="6" y1="18" x2="6.01" y2="18"/>
                </svg>
                <h2 class="text-title">{t("dashboard.hosts.title")}</h2>
            </div>
        {#each Object.entries(agents.byEndpoint).filter(([e]) => e !== "") as [endpoint, agent] (endpoint)}
            {@const online = agents.statuses[endpoint]?.status === "online"}
            <div class="host-row" data-audit-row="center">
                <span
                    class="status-dot"
                    class:online
                    role="img"
                    aria-label={online ? t("host.online") : t("host.offline")}
                ></span>
                <span class="text-body-medium host-name">{agent.name || agent.endpoint}</span>
                {#if isExpanded.current}
                    <div class="host-actions">
                        <button type="button" onclick={() => void renameHost(agent.url)}>
                            {t("dashboard.hosts.rename")}
                        </button>
                        <button type="button" onclick={() => (removeTarget = agent.url)}>
                            {t("dashboard.hosts.remove")}
                        </button>
                    </div>
                {:else}
                    <MenuButton
                        items={[
                            { label: t("dashboard.hosts.rename"), onSelect: () => void renameHost(agent.url) },
                            {
                                label: t("dashboard.hosts.remove"),
                                danger: true,
                                onSelect: () => (removeTarget = agent.url),
                            },
                        ]}
                    />
                {/if}
            </div>
        {/each}

        <form class="add-form" onsubmit={addHost} data-audit-column>
            <input
                type="url"
                placeholder="https://host:5001"
                aria-label={t("host.url")}
                required
                bind:value={addUrl}
            />
            <input
                type="text"
                placeholder={t("host.username")}
                aria-label={t("host.username")}
                autocomplete="username"
                required
                bind:value={addUsername}
            />
            <input
                type="password"
                placeholder={t("host.password")}
                aria-label={t("host.password")}
                autocomplete="new-password"
                required
                bind:value={addPassword}
            />
            <input
                type="text"
                placeholder={t("host.name")}
                aria-label={t("host.name")}
                bind:value={addName}
            />
            {#if addError !== null}
                <p class="error text-label">{addError}</p>
            {/if}
            <button type="submit" class="primary" disabled={adding}>{t("dashboard.hosts.add")}</button>
        </form>
        </div>
    </div>
</div>

<ConfirmDialog
    open={removeTarget !== null}
    title={t("dashboard.hosts.remove")}
    message={removeTarget !== null ? t("dashboard.hosts.removeConfirm", { url: removeTarget }) : ""}
    danger
    onconfirm={confirmRemove}
    oncancel={() => (removeTarget = null)}
/>

<style>
    .dashboard {
        display: flex;
        flex-direction: column;
        gap: var(--space-4);
        padding: var(--space-4);
        max-width: 100%;
    }

    .header-row {
        display: flex;
        align-items: center;
        gap: var(--space-2);
        height: var(--size-control-lg);
    }

    .grid {
        display: flex;
        flex-direction: column;
        gap: var(--space-4);
    }

    @media (width >= 1200px) {
        .grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
        }
    }

    .card {
        padding: var(--space-4);
        border-radius: var(--radius-md);
        box-shadow: inset 0 0 0 1px var(--m3c-outline-variant);
        background: var(--m3c-surface-container-low);
    }

    .card-title-row {
        display: flex;
        align-items: center;
        gap: var(--space-2);
        margin-block-end: var(--space-2);
    }

    .card-icon {
        width: var(--size-icon-md);
        height: var(--size-icon-md);
        color: var(--m3c-primary);
        flex-shrink: 0;
    }

    .counts {
        display: flex;
        gap: var(--space-3);
        padding: var(--space-3);
    }

    .count {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: var(--space-1);
        padding: var(--space-3);
        border-radius: var(--radius-sm);
        background: var(--m3c-surface-container);
        box-shadow: inset 0 0 0 1px var(--m3c-outline-variant);
        color: var(--m3c-on-surface);
        text-decoration: none;
        flex: 1;
    }

    .count:hover {
        background: var(--m3c-surface-container-high);
    }

    .count-dot {
        width: var(--space-2);
        height: var(--space-2);
        border-radius: 50%;
        flex-shrink: 0;
    }

    .active-dot {
        background: var(--m3c-tertiary);
    }

    .exited-dot {
        background: var(--m3c-error);
    }

    .inactive-dot {
        background: var(--m3c-outline);
    }

    .count-value {
        font-variant-numeric: tabular-nums;
        font-weight: 700;
    }

    .count-label {
        color: var(--m3c-on-surface-variant);
        font-weight: 500;
    }

    .command {
        display: block;
        width: 100%;
        min-height: var(--space-12);
        margin-block: var(--space-2);
        padding: var(--space-3);
        border: 1px solid var(--m3c-outline-variant);
        border-radius: var(--radius-xs);
        background: var(--m3c-surface-container-lowest);
        color: var(--m3c-on-surface);
        font-family: "JetBrains Mono", monospace;
        font-size: 13px;
        resize: vertical;
    }

    .command:focus {
        border-color: var(--m3c-primary);
    }

    .error {
        color: var(--m3c-error);
        margin-block-end: var(--space-2);
    }

    .primary {
        align-self: flex-start;
        height: var(--size-control-md);
        padding-inline: var(--space-4);
        border: 1px solid transparent;
        border-radius: var(--radius-xl);
        background: var(--m3c-primary);
        color: var(--m3c-on-primary);
        font-weight: 600;
        font-size: 13px;
        cursor: pointer;
    }

    .primary:disabled {
        opacity: 0.5;
        cursor: default;
    }

    .host-row {
        display: flex;
        align-items: center;
        gap: var(--space-3);
        height: var(--size-control-lg);
        padding-inline: var(--space-3);
        border-radius: var(--radius-sm);
        background: var(--m3c-surface-container);
        box-shadow: inset 0 0 0 1px var(--m3c-outline-variant);
        margin-block-end: var(--space-2);
    }

    .host-row:hover {
        background: var(--m3c-surface-container-high);
    }

    .status-dot {
        width: var(--space-2);
        height: var(--space-2);
        border-radius: 50%;
        background: var(--m3c-error);
        flex-shrink: 0;
    }

    .status-dot.online {
        background: var(--m3c-tertiary);
    }

    .host-name {
        flex: 1;
        font-weight: 500;
    }

    .host-actions {
        display: flex;
        gap: var(--space-2);
    }

    .host-actions button {
        height: var(--size-control-sm);
        padding-inline: var(--space-3);
        border: 1px solid var(--m3c-outline-variant);
        border-radius: var(--radius-xs);
        background: var(--m3c-surface-container-high);
        color: var(--m3c-on-surface);
        font-size: 12px;
        cursor: pointer;
    }

    .host-actions button:hover {
        background: var(--m3c-surface-container-highest);
    }

    @media (pointer: coarse) {
        .host-actions button {
            height: var(--size-control-lg);
        }
    }

    .add-form {
        display: flex;
        flex-direction: column;
        gap: var(--space-2);
        margin-block-start: var(--space-3);
        padding-block-start: var(--space-3);
        box-shadow: inset 0 1px 0 var(--m3c-outline-variant);
    }

    .add-form input {
        height: var(--size-control-md);
        padding-inline: var(--space-3);
        padding-block: 0;
        border: 1px solid var(--m3c-outline-variant);
        border-radius: var(--radius-xs);
        background: var(--m3c-surface-container-lowest);
        color: var(--m3c-on-surface);
        font-size: 13px;
    }

    .add-form input:focus {
        border-color: var(--m3c-primary);
    }
</style>
