// frontend/src/pages/Stack.svelte
<script lang="ts">
    import { MediaQuery } from "svelte/reactivity";
    import { onMount } from "svelte";
    import { request } from "../lib/connection.svelte.ts";
    import { t } from "../lib/stores/i18n.svelte.ts";
    import { agents } from "../lib/stores/agents.svelte.ts";
    import { stacks } from "../lib/stores/stacks.svelte.ts";
    import { settings } from "../lib/stores/settings.svelte.ts";
    import { toastError, toastResult } from "../lib/stores/toast.svelte.ts";
    import { route, navigate, registerBeforeLeave } from "../router.svelte.ts";
    import { CREATED, DRAFT, EXITED, RUNNING, type StackSummary } from "../../../common/stack.ts";
    import CodeEditor from "../components/CodeEditor.svelte";
    import ConfirmDialog from "../components/ConfirmDialog.svelte";
    import MenuButton, { type MenuItemSpec } from "../components/MenuButton.svelte";
    import ServiceCard from "../components/ServiceCard.svelte";
    import StatusChip from "../components/StatusChip.svelte";
    import TerminalView from "../components/TerminalView.svelte";
    import { composeTerminalName, logsTerminalName } from "../../../common/terminal.ts";
    import { parseCompose, serialiseWithComments, expandForDisplay, parseEnv, type ComposeConfig } from "./compose/sync.ts";

    const isMedium = new MediaQuery("width >= 600px");

    const stackName = $derived(route.params.name ?? "");
    const endpoint = $derived(route.params.endpoint ?? "");
    const isCreate = $derived(stackName === "" && route.path === "/compose");

    const hostLabel = $derived(endpoint === "" ? "" : agents.byEndpoint[endpoint]?.name || endpoint);
    const hostOffline = $derived(endpoint !== "" && agents.statuses[endpoint]?.status !== "online");

    const stackKey = $derived(`${stackName} ${endpoint}`);
    const summary = $derived<StackSummary | undefined>(stacks.byKey[stackKey]);
    const stackStatus = $derived(summary?.status ?? 0);

    let mode = $state<"view" | "edit">("view");
    let activeTab = $state<"compose" | "env">("compose");

    let yamlText = $state("");
    let initialYaml = $state("");
    let envText = $state("");
    let initialEnv = $state("");

    let dirty = $state(false);
    // Per-tab, so the tab strip can mark which document has unsaved edits rather than lighting
    // both up whenever either changed.
    const composeDirty = $derived(yamlText !== initialYaml);
    const envDirty = $derived(envText !== initialEnv);
    let yamlError = $state<string | null>(null);
    let submitting = $state(false);
    let deleteConfirm = $state(false);

    let config = $state<ComposeConfig>({ services: {} });
    let serviceNames = $derived(Object.keys(config.services ?? {}));
    let availableNetworks = $state<string[]>([]);
    let serviceStatus = $state<Record<string, { state?: string; health?: string; status?: string; shellAvailable?: boolean }[]>>({});
    let stats = $state<Record<string, { Name: string; CPUPerc?: string; MemUsage?: string }[]>>({});
    let expanded = $state<ComposeConfig>({});

    function globalEnvText(): string {
        return settings.values?.globalENV ?? "";
    }

    function mergedEnv(): Record<string, string> {
        return { ...parseEnv(globalEnvText()), ...parseEnv(envText) };
    }

    function refreshExpanded(): void {
        const result = expandForDisplay(yamlText, mergedEnv());
        expanded = result.config;
    }

    async function loadStack(): Promise<void> {
        try {
            const result = await request<{ stack: { composeYAML: string; composeENV: string } }>(endpoint, "stack.get", { name: stackName });
            yamlText = result.stack.composeYAML;
            initialYaml = result.stack.composeYAML;
            envText = result.stack.composeENV;
            initialEnv = result.stack.composeENV;
            const parsed = parseCompose(yamlText);
            config = parsed.config;
            refreshExpanded();
            dirty = false;
        } catch (error) {
            toastError(error);
        }
    }

    $effect(() => {
        if (isCreate) {
            mode = "edit";
            const draft = sessionStorage.getItem("docknight-compose-draft");
            if (draft !== null) {
                yamlText = draft;
                initialYaml = "";
                sessionStorage.removeItem("docknight-compose-draft");
                const parsed = parseCompose(yamlText);
                config = parsed.config;
                refreshExpanded();
                dirty = true;
            }
        } else if (stackName !== "") {
            void loadStack();
        }
    });

    $effect(() => {
        if (endpoint !== undefined) {
            void request<Array<{ Name: string }>>(endpoint, "docker.networks", undefined)
                .then((nets) => {
                    availableNetworks = nets.map((n) => n.Name);
                })
                .catch(() => {
                    availableNetworks = [];
                });
        }
    });

    $effect(() => {
        if (stackName === "" || isCreate) return;
        let cancelled = false;
        async function poll(): Promise<void> {
            try {
                const [statusResult, statsResult] = await Promise.all([
                    request<{ services?: Record<string, { state?: string; health?: string; status?: string; shellAvailable?: boolean }[]> }>(endpoint, "stack.serviceStatus", { name: stackName }),
                    request<{ stats?: Record<string, { Name: string; CPUPerc?: string; MemUsage?: string }[]> }>(endpoint, "docker.stats", undefined),
                ]);
                if (cancelled) return;
                serviceStatus = statusResult?.services ?? {};
                if (statsResult?.stats) {
                    stats = statsResult.stats;
                }
            } catch {
                // keep last known values
            }
        }
        void poll();
        const timer = setInterval(() => void poll(), 3000);
        return () => {
            cancelled = true;
            clearInterval(timer);
        };
    });

    function onEditorInput(val: string): void {
        yamlText = val;
        dirty = yamlText !== initialYaml || envText !== initialEnv;
        const parsed = parseCompose(val);
        if (parsed.error !== null) {
            yamlError = parsed.error;
        } else {
            config = parsed.config;
            yamlError = null;
            refreshExpanded();
        }
    }

    function onEditorFocus(): void {}
    function onEditorBlur(): void {}

    async function saveDraft(): Promise<void> {
        submitting = true;
        try {
            await request(endpoint, "stack.save", {
                name: stackName,
                composeYAML: yamlText,
                composeENV: envText,
                isCreate,
            });
            initialYaml = yamlText;
            initialEnv = envText;
            dirty = false;
            toastResult(t("toast.saved"));
            if (isCreate) {
                await navigate(`/compose/${stackName}`);
            }
        } catch (error) {
            toastError(error);
        } finally {
            submitting = false;
        }
    }

    async function deploy(): Promise<void> {
        submitting = true;
        try {
            await request(endpoint, "stack.save", {
                name: stackName,
                composeYAML: yamlText,
                composeENV: envText,
                isCreate,
            });
            await request(endpoint, "stack.deploy", { name: stackName }, { timeout: 0 });
            initialYaml = yamlText;
            initialEnv = envText;
            dirty = false;
            mode = "view";
            toastResult(t("toast.saved"));
        } catch (error) {
            toastError(error);
        } finally {
            submitting = false;
        }
    }

    function discard(): void {
        yamlText = initialYaml;
        envText = initialEnv;
        dirty = false;
        const parsed = parseCompose(yamlText);
        config = parsed.config;
        refreshExpanded();
        mode = "view";
    }

    async function stackAction(action: string): Promise<void> {
        submitting = true;
        try {
            await request(endpoint, action, { name: stackName });
            toastResult(t("toast.saved"));
        } catch (error) {
            toastError(error);
        } finally {
            submitting = false;
        }
    }

    async function serviceAction(action: string, service: string): Promise<void> {
        try {
            await request(endpoint, action, { stack: stackName, service });
        } catch (error) {
            toastError(error);
        }
    }

    function removeService(name: string): void {
        const next = { ...config };
        if (next.services !== undefined) {
            delete next.services[name];
            config = next;
            const res = serialiseWithComments(next, null);
            yamlText = res.text;
            dirty = true;
        }
    }

    function statsForService(name: string) {
        const containerNames = new Set((serviceStatus[name] ?? []).map((s: { name?: string }) => s.name));
        return Object.values(stats).filter((entry: { Name?: string }) => containerNames.has(entry.Name));
    }

    function getServiceStatus(name: string) {
        return serviceStatus[name];
    }

    function getExpandedPorts(name: string): string[] | undefined {
        const s = (expanded.services ?? {}) as Record<string, { ports?: string[] }>;
        return s[name]?.ports;
    }

    function statusWord(status: number): string {
        if (status === RUNNING) return "running";
        if (status === EXITED) return "exited";
        if (status === CREATED) return "created";
        if (status === DRAFT) return "draft";
        return "unknown";
    }

    const moreMenuItems = $derived.by((): MenuItemSpec[] => [
        { label: t("stack.action.down"), disabled: submitting, onSelect: () => void stackAction("stack.down") },
        { label: t("stack.action.delete"), danger: true, onSelect: () => (deleteConfirm = true) },
    ]);

    // The compact bar has room for Edit and Start only; Restart, Stop, and Update would
    // otherwise be reachable on a wide viewport and nowhere else, so the menu carries them.
    // Each mirrors the disabled state of the wide-viewport button it stands in for.
    const compactMoreMenuItems = $derived.by((): MenuItemSpec[] => [
        { label: t("stack.action.restart"), disabled: submitting, onSelect: () => void stackAction("stack.restart") },
        { label: t("stack.action.stop"), disabled: submitting, onSelect: () => void stackAction("stack.stop") },
        { label: t("stack.action.update"), disabled: submitting, onSelect: () => void stackAction("stack.update") },
        ...moreMenuItems,
    ]);

    const editMenuItems = $derived.by((): MenuItemSpec[] => [
        { label: t("stack.action.save"), disabled: submitting, onSelect: () => void saveDraft() },
        { label: t("stack.action.discard"), disabled: submitting, onSelect: () => void discard() },
    ]);

    onMount(() => {
        return registerBeforeLeave(() => {
            if (dirty) {
                return confirm(t("stack.unsavedChanges"));
            }
            return true;
        });
    });
</script>

<div class="gcp-stack-page" data-audit-root>
    {#if isCreate}
        <div class="gcp-stack-header" data-audit-row="center">
            <h1 class="text-headline">{t("stack.list.createFirst")}</h1>
        </div>
    {:else}
        <div class="gcp-stack-header" data-audit-row="center">
            <h1 class="text-headline">{stackName}</h1>
            {#if endpoint !== ""}
                <span class="gcp-host-badge text-label">{hostLabel}</span>
            {/if}
            <StatusChip status={statusWord(stackStatus)} />
        </div>

        {#if hostOffline}
            <div class="gcp-offline-banner text-body-medium">{t("stack.hostOffline")}</div>
        {/if}

        {#if isMedium.current}
            <div class="gcp-action-bar action-bar" data-audit-row="center">
                {#if mode === "edit"}
                    <button type="button" class="btn btn-filled" disabled={submitting} onclick={deploy}>
                        {t("stack.action.deploy")}
                    </button>
                    <button type="button" class="btn btn-outlined" disabled={submitting} onclick={saveDraft}>
                        {t("stack.action.save")}
                    </button>
                    <button type="button" class="btn btn-text" disabled={submitting} onclick={discard}>
                        {t("stack.action.discard")}
                    </button>
                {:else}
                    <button type="button" class="btn btn-outlined" onclick={() => (mode = "edit")}>
                        {t("stack.action.edit")}
                    </button>
                    <button type="button" class="btn btn-outlined" disabled={submitting} onclick={() => void stackAction("stack.start")}>
                        {t("stack.action.start")}
                    </button>
                    <button type="button" class="btn btn-outlined" disabled={submitting} onclick={() => void stackAction("stack.restart")}>
                        {t("stack.action.restart")}
                    </button>
                    <button type="button" class="btn btn-outlined" disabled={submitting} onclick={() => void stackAction("stack.stop")}>
                        {t("stack.action.stop")}
                    </button>
                    <button type="button" class="btn btn-outlined" disabled={submitting} onclick={() => void stackAction("stack.update")}>
                        {t("stack.action.update")}
                    </button>
                    <MenuButton items={moreMenuItems} />
                {/if}
            </div>
        {/if}

        <div class="gcp-editors">
            <div class="gcp-tabs" role="tablist" data-audit-row="center">
                <button
                    type="button"
                    role="tab"
                    aria-selected={activeTab === "compose"}
                    class:active={activeTab === "compose"}
                    onclick={() => (activeTab = "compose")}
                >
                    {t("stack.tab.compose")}
                    {#if composeDirty}
                        <span class="gcp-tab-dot" aria-hidden="true"></span>
                    {/if}
                </button>
                <button
                    type="button"
                    role="tab"
                    aria-selected={activeTab === "env"}
                    class:active={activeTab === "env"}
                    onclick={() => (activeTab = "env")}
                >
                    {t("stack.tab.env")}
                    {#if envDirty}
                        <span class="gcp-tab-dot" aria-hidden="true"></span>
                    {/if}
                </button>
            </div>
            {#if activeTab === "compose"}
                <div class="gcp-editor-pane">
                    <CodeEditor
                        value={yamlText}
                        oninput={onEditorInput}
                        onfocus={onEditorFocus}
                        onblur={onEditorBlur}
                        ariaLabel={t("stack.tab.compose")}
                    />
                    {#if yamlError !== null}
                        <p class="gcp-yaml-error text-label">{yamlError}</p>
                    {/if}
                </div>
            {:else}
                <div class="gcp-editor-pane">
                    <CodeEditor
                        value={envText}
                        oninput={(v) => {
                            envText = v;
                            dirty = yamlText !== initialYaml || envText !== initialEnv;
                            refreshExpanded();
                        }}
                        ariaLabel={t("stack.tab.env")}
                    />
                </div>
            {/if}
        </div>

        <div class="gcp-services" data-audit-column>
            {#each serviceNames as name (name)}
                {@const currentService = (config.services ?? {})[name]}
                {#if currentService !== undefined}
                    <ServiceCard
                        {name}
                        service={currentService as never}
                        editable={mode === "edit"}
                        multiService={serviceNames.length > 1}
                        status={getServiceStatus(name)}
                        stats={statsForService(name)}
                        expandedPorts={getExpandedPorts(name)}
                        {availableNetworks}
                        onstart={(n) => void serviceAction("service.start", n)}
                        onstop={(n) => void serviceAction("service.stop", n)}
                        onrestart={(n) => void serviceAction("service.restart", n)}
                        onremove={removeService}
                    />
                {/if}
            {/each}
        </div>

        <div class="gcp-terminals" data-audit-column>
            <TerminalView
                {endpoint}
                terminal={composeTerminalName(endpoint, stackName)}
                interactive={false}
                rows={8}
            />
            <TerminalView
                {endpoint}
                terminal={logsTerminalName(endpoint, stackName)}
                interactive={false}
                rows={20}
            />
        </div>

        {#if !isMedium.current}
            <div class="gcp-bottom-bar bottom-app-bar action-bar" data-audit-row="center">
                <a
                    href="/"
                    class="gcp-back-action"
                    aria-label={t("action.back")}
                    onclick={(e) => {
                        e.preventDefault();
                        void navigate("/");
                    }}
                >
                    ←
                </a>
                {#if mode === "edit"}
                    <button type="button" class="btn btn-filled" disabled={submitting} onclick={deploy}>
                        {t("stack.action.deploy")}
                    </button>
                    <MenuButton items={editMenuItems} />
                {:else}
                    <button type="button" class="btn btn-filled" onclick={() => (mode = "edit")}>
                        {t("stack.action.edit")}
                    </button>
                    <button type="button" class="btn btn-outlined" disabled={submitting} onclick={() => void stackAction("stack.start")}>
                        {t("stack.action.start")}
                    </button>
                    <MenuButton items={compactMoreMenuItems} />
                {/if}
            </div>
        {/if}
    {/if}
</div>

<ConfirmDialog
    open={deleteConfirm}
    title={t("stack.action.delete")}
    message={t("stack.action.deleteConfirm", { name: stackName })}
    danger
    onconfirm={() => {
        deleteConfirm = false;
        void stackAction("stack.delete").then(() => void navigate("/"));
    }}
    oncancel={() => (deleteConfirm = false)}
/>

<style>
    .gcp-stack-page {
        display: flex;
        flex-direction: column;
        padding: var(--space-6);
        gap: var(--space-6);
    }

    @media (width < 600px) {
        .gcp-stack-page {
            padding: var(--space-4);
            gap: var(--space-4);
        }
    }

    .gcp-stack-header {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        gap: var(--space-3);
        min-height: var(--size-control-md);
    }

    .gcp-stack-header h1 {
        min-width: 0;
        overflow-wrap: anywhere;
    }

    .gcp-host-badge {
        padding-inline: var(--chip-padding-inline);
        height: var(--chip-height);
        display: inline-flex;
        align-items: center;
        border-radius: var(--radius-xs);
        background: var(--m3c-surface-container-high);
        color: var(--m3c-on-surface-variant);
    }

    .gcp-offline-banner {
        padding: var(--space-3);
        border-radius: var(--radius-xs);
        background: var(--m3c-error-container);
        color: var(--m3c-on-error-container);
    }

    .gcp-action-bar {
        display: flex;
        flex-wrap: wrap;
        gap: var(--space-2);
    }

    .gcp-tabs button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        block-size: var(--size-control-md);
        padding-block: 0;
        padding-inline: var(--control-padding-inline);
        border: none;
        border-radius: var(--radius-round);
        background: transparent;
        color: var(--m3c-on-surface-variant);
        font-family: inherit;
        font-weight: 500;
        font-size: var(--control-font-size);
        cursor: pointer;
        transition:
            background var(--duration-fast) var(--ease-standard),
            color var(--duration-fast) var(--ease-standard);
    }

    .gcp-tabs button:hover {
        background: var(--m3c-surface-container-high);
    }

    .gcp-tabs button.active {
        background: var(--m3c-secondary-container);
        color: var(--m3c-on-secondary-container);
    }

    .gcp-tab-dot {
        inline-size: var(--space-2);
        block-size: var(--space-2);
        margin-inline-start: var(--space-2);
        border-radius: var(--radius-round);
        background: currentcolor;
        flex-shrink: 0;
    }

    .gcp-editors {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
    }

    .gcp-tabs {
        display: flex;
        gap: var(--space-2);
    }

    .gcp-editor-pane {
        min-width: 0;
        block-size: var(--measure-editor-lg);
        display: flex;
        flex-direction: column;
    }

    .gcp-yaml-error {
        color: var(--m3c-error);
        margin-block-start: var(--space-2);
    }

    .gcp-services {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
    }

    .gcp-terminals {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
    }

    .gcp-bottom-bar {
        position: sticky;
        inset-block-end: 0;
        height: var(--size-bottom-bar);
        padding-inline: var(--space-4);
        background: var(--m3c-surface-container);
        border-block-start: 1px solid var(--m3c-outline-variant);
        display: flex;
        align-items: center;
        gap: var(--space-2);
        z-index: 10;
    }

    .gcp-bottom-bar .btn-filled {
        flex: 1;
    }

    .gcp-back-action {
        display: flex;
        align-items: center;
        justify-content: center;
        width: var(--size-control-lg);
        height: var(--size-control-lg);
        color: var(--m3c-on-surface);
        text-decoration: none;
        flex-shrink: 0;
    }
</style>

// frontend/src/pages/Stack.tsx
import { useMutation, useQuery } from "@tanstack/react-query";
import { type FormEvent, type ReactElement, useEffect, useMemo, useRef, useState } from "react";
import type { ServiceInstance, StackDetail } from "../../../common/stack.ts";
import { CREATED, DRAFT, EXITED, RUNNING } from "../../../common/stack.ts";
import { composeTerminalName, logsTerminalName } from "../../../common/terminal.ts";
import BottomSheet from "../components/BottomSheet.tsx";
import CodeEditor from "../components/CodeEditor.tsx";
import ConfirmDialog from "../components/ConfirmDialog.tsx";
import ServiceCard from "../components/ServiceCard.tsx";
import StatusChip from "../components/StatusChip.tsx";
import TerminalView from "../components/TerminalView.tsx";
import { elementValue, useElementEvent } from "../lib/dom-events.ts";
import { useT } from "../lib/i18n.ts";
import { useSizeClass } from "../lib/media.ts";
import { qk } from "../lib/query.ts";
import { agents, stackKey as makeStackKey, stacks } from "../lib/push.ts";
import { linkHandler, navigate, registerBeforeLeave, useRoute } from "../lib/router.ts";
import { useStore } from "../lib/store.ts";
import { toastError, toastSuccess } from "../lib/toast.ts";
import { request } from "../lib/transport.ts";
import { useParams } from "../routes.ts";
import {
    type ComposeConfig,
    expandForDisplay,
    parseCompose,
    parseEnv,
    serialiseWithComments,
} from "./compose/sync.ts";

interface ContainerStats {
    Name?: string;
    CPUPerc?: string;
    MemUsage?: string;
}

const STATUS_WORD: Record<number, string> = {
    [RUNNING]: "running",
    [EXITED]: "exited",
    [CREATED]: "created",
    [DRAFT]: "draft",
};

const DRAFT_KEY = "docknight-compose-draft";
const STATUS_POLL_MS = 3000;

export default function Stack(): ReactElement {
    const { t } = useT();
    const sizeClass = useSizeClass();
    const params = useParams();
    const { path } = useRoute();
    const { byKey } = useStore(stacks);
    const { byEndpoint, statuses } = useStore(agents);

    const stackName = params.name ?? "";
    const endpoint = params.endpoint ?? "";
    const isCreate = stackName === "" && path === "/compose";

    const hostLabel = endpoint === "" ? "" : byEndpoint[endpoint]?.name || endpoint;
    const hostOffline = endpoint !== "" && statuses[endpoint]?.status !== "online";
    const summary = byKey[makeStackKey(stackName, endpoint)];

    const [mode, setMode] = useState<"view" | "edit">(isCreate ? "edit" : "view");
    const [activeTab, setActiveTab] = useState<"compose" | "env">("compose");
    const [newName, setNewName] = useState("");
    const newNameRef = useRef<HTMLElement>(null);
    useElementEvent(newNameRef, "input", () => setNewName(elementValue(newNameRef)));

    // A converted `docker run` command arrives through session storage from the dashboard and
    // is consumed once, during the first render of the create screen.
    const [yamlText, setYamlText] = useState(() => {
        if (!isCreate) return "";
        const draft = sessionStorage.getItem(DRAFT_KEY);
        if (draft === null) return "";
        sessionStorage.removeItem(DRAFT_KEY);
        return draft;
    });
    const [initialYaml, setInitialYaml] = useState("");
    const [envText, setEnvText] = useState("");
    const [initialEnv, setInitialEnv] = useState("");
    const [config, setConfig] = useState<ComposeConfig>(() => parseCompose(yamlText).config);
    const [yamlError, setYamlError] = useState<string | null>(null);
    const [deleteConfirm, setDeleteConfirm] = useState(false);
    const [overflowOpen, setOverflowOpen] = useState(false);

    const composeDirty = yamlText !== initialYaml;
    const envDirty = envText !== initialEnv;
    const dirty = composeDirty || envDirty;

    const settingsQuery = useQuery({
        queryKey: qk.settings(),
        queryFn: () => request<{ globalENV?: string }>("", "settings.get", undefined),
        staleTime: 60_000,
    });
    const globalEnv = settingsQuery.data?.globalENV ?? "";

    const stackQuery = useQuery({
        queryKey: qk.stack(endpoint, stackName),
        queryFn: () => request<{ stack: StackDetail }>(endpoint, "stack.get", { name: stackName }),
        enabled: !isCreate && stackName !== "",
    });

    // The editors are local state seeded from the fetched document. Every refetch hands back a
    // fresh object, so the seed compares content. While the user has unsaved edits nothing is
    // adopted and nothing is recorded as seen, so the pending server copy lands once they settle.
    const loaded = stackQuery.data?.stack;
    // StackDetail owns editability. The push summary only identifies an external stack.
    const stackIsManaged = loaded?.managed === true;
    const stackIsExternal = loaded?.managed === false || (loaded === undefined && summary?.managed === false);
    const editing = mode === "edit" && (isCreate || stackIsManaged);
    const [seenStack, setSeenStack] = useState<{ yaml: string; env: string } | null>(null);
    if (
        loaded !== undefined &&
        !dirty &&
        (seenStack === null ||
            seenStack.yaml !== loaded.composeYAML ||
            seenStack.env !== loaded.composeENV)
    ) {
        setSeenStack({ yaml: loaded.composeYAML, env: loaded.composeENV });
        setYamlText(loaded.composeYAML);
        setInitialYaml(loaded.composeYAML);
        setEnvText(loaded.composeENV);
        setInitialEnv(loaded.composeENV);
        setConfig(parseCompose(loaded.composeYAML).config);
        setYamlError(null);
    }

    // The variable-expanded view is a pure function of the two documents and the global env.
    const expanded = useMemo((): ComposeConfig => {
        const merged = { ...parseEnv(globalEnv), ...parseEnv(envText) };
        return expandForDisplay(yamlText, merged).config;
    }, [yamlText, envText, globalEnv]);

    const networksQuery = useQuery({
        queryKey: qk.networks(endpoint),
        queryFn: () => request<{ networks: string[] }>(endpoint, "docker.networks", undefined),
    });
    const availableNetworks = networksQuery.data?.networks ?? [];

    const statusQuery = useQuery({
        queryKey: qk.serviceStatus(endpoint, stackName),
        queryFn: () =>
            request<{ services?: Record<string, ServiceInstance[]> }>(endpoint, "stack.serviceStatus", {
                name: stackName,
            }),
        enabled: !isCreate && stackName !== "",
        refetchInterval: STATUS_POLL_MS,
    });
    const serviceStatus = statusQuery.data?.services ?? {};

    const statsQuery = useQuery({
        queryKey: qk.dockerStats(endpoint),
        queryFn: () =>
            request<{ stats?: Record<string, ContainerStats> }>(endpoint, "docker.stats", undefined),
        enabled: !isCreate,
        refetchInterval: STATUS_POLL_MS,
    });
    const stats = statsQuery.data?.stats ?? {};

    useEffect(
        () =>
            registerBeforeLeave(() => (dirty ? confirm(t("stack.unsavedChanges")) : true)),
        [dirty, t],
    );

    const saveMutation = useMutation({
        mutationFn: (target: string) =>
            request(endpoint, "stack.save", {
                name: target,
                composeYAML: yamlText,
                composeENV: envText,
                isCreate,
            }),
        onError: toastError,
    });

    const deployMutation = useMutation({
        mutationFn: (target: string) =>
            request(endpoint, "stack.deploy", { name: target }, { timeout: 0 }),
        onError: toastError,
    });

    const lifecycleMutation = useMutation({
        mutationFn: (action: string) => request(endpoint, action, { name: stackName }),
        onSuccess: () => toastSuccess(t("toast.saved")),
        onError: toastError,
    });

    const serviceMutation = useMutation({
        mutationFn: (vars: { action: string; service: string }) =>
            request(endpoint, vars.action, { stack: stackName, service: vars.service }),
        onError: toastError,
    });

    const submitting =
        saveMutation.isPending || deployMutation.isPending || lifecycleMutation.isPending;

    const targetName = isCreate ? newName.trim() : stackName;

    async function saveDraft(): Promise<void> {
        if (targetName === "") return;
        await saveMutation.mutateAsync(targetName);
        setInitialYaml(yamlText);
        setInitialEnv(envText);
        toastSuccess(t("toast.saved"));
        if (isCreate) await navigate(`/compose/${targetName}`);
    }

    async function deploy(): Promise<void> {
        if (targetName === "") return;
        await saveMutation.mutateAsync(targetName);
        await deployMutation.mutateAsync(targetName);
        setInitialYaml(yamlText);
        setInitialEnv(envText);
        setMode("view");
        toastSuccess(t("toast.saved"));
        if (isCreate) await navigate(`/compose/${targetName}`);
    }

    function discard(): void {
        setYamlText(initialYaml);
        setEnvText(initialEnv);
        setConfig(parseCompose(initialYaml).config);
        setYamlError(null);
        setMode("view");
    }

    function onComposeInput(value: string): void {
        setYamlText(value);
        const parsed = parseCompose(value);
        if (parsed.error !== null) {
            setYamlError(parsed.error);
            return;
        }
        setConfig(parsed.config);
        setYamlError(null);
    }

    function applyServicePatch(name: string, patch: Record<string, unknown>): void {
        const services = { ...(config.services ?? {}) };
        const current = services[name];
        if (current === undefined) return;
        services[name] = { ...current, ...patch };
        const next: ComposeConfig = { ...config, services };
        setConfig(next);
        setYamlText(serialiseWithComments(next, null).text);
    }

    function removeService(name: string): void {
        const services = { ...(config.services ?? {}) };
        delete services[name];
        const next: ComposeConfig = { ...config, services };
        setConfig(next);
        setYamlText(serialiseWithComments(next, null).text);
    }

    function statsForService(name: string): ContainerStats[] {
        const containerNames = new Set((serviceStatus[name] ?? []).map((instance) => instance.name));
        return Object.values(stats).filter(
            (entry) => entry.Name !== undefined && containerNames.has(entry.Name),
        );
    }

    function expandedPortsFor(name: string): string[] | undefined {
        const services = expanded.services ?? {};
        const service = services[name];
        if (service === undefined) return undefined;
        const ports = service.ports;
        return Array.isArray(ports) ? ports.filter((port) => typeof port === "string") : undefined;
    }

    const serviceNames = Object.keys(config.services ?? {});

    const editorPane = (
        <mdui-card>
            <div className="section">
                <mdui-tabs
                    value={activeTab}
                    full-width
                    onClick={(event) => {
                        // The tab strip is two controls; reading the clicked tab's own value keeps
                        // this independent of the component's change event timing.
                        const target = event.target;
                        if (!(target instanceof HTMLElement)) return;
                        const tab = target.closest("mdui-tab");
                        const value = tab?.getAttribute("value");
                        if (value === "compose" || value === "env") setActiveTab(value);
                    }}
                >
                    <mdui-tab value="compose">
                        {t("stack.tab.compose")}
                        {composeDirty ? <mdui-badge slot="badge" /> : null}
                    </mdui-tab>
                    <mdui-tab value="env">
                        {t("stack.tab.env")}
                        {envDirty ? <mdui-badge slot="badge" /> : null}
                    </mdui-tab>
                </mdui-tabs>

                {activeTab === "compose" ? (
                    <>
                        <CodeEditor
                            value={yamlText}
                            onChange={onComposeInput}
                            ariaLabel={t("stack.tab.compose")}
                        />
                        {yamlError !== null ? (
                            <p className="type-body-small danger-text" role="alert">
                                {yamlError}
                            </p>
                        ) : null}
                    </>
                ) : (
                    <CodeEditor
                        value={envText}
                        onChange={setEnvText}
                        ariaLabel={t("stack.tab.env")}
                    />
                )}
            </div>
        </mdui-card>
    );

    if (isCreate) {
        return (
            <div className="page stack-page">
                <div className="page-header stack-page__header">
                    <h1 className="type-headline-small">{t("stack.list.createFirst")}</h1>
                </div>

                <form
                    className="form-column"
                    onSubmit={(event: FormEvent<HTMLFormElement>) => {
                        event.preventDefault();
                        void saveDraft();
                    }}
                >
                    <mdui-text-field
                        ref={newNameRef}
                        variant="outlined"
                        label={t("stack.create.name")}
                        required
                        autocapitalize="none"
                        autocorrect="off"
                        spellcheck={false}
                    />
                </form>

                {editorPane}

                <div className="row">
                    <mdui-button
                        variant="filled"
                        disabled={submitting || targetName === ""}
                        loading={submitting}
                        onClick={() => void deploy()}
                    >
                        {t("stack.action.deploy")}
                    </mdui-button>
                    <mdui-button
                        variant="tonal"
                        disabled={submitting || targetName === ""}
                        onClick={() => void saveDraft()}
                    >
                        {t("stack.action.save")}
                    </mdui-button>
                </div>
            </div>
        );
    }

    const viewActions = [
        { label: t("stack.action.start"), action: "stack.start", icon: "play_arrow--outlined" },
        { label: t("stack.action.restart"), action: "stack.restart", icon: "restart_alt--outlined" },
        { label: t("stack.action.stop"), action: "stack.stop", icon: "stop--outlined" },
        { label: t("stack.action.update"), action: "stack.update", icon: "system_update_alt--outlined" },
        { label: t("stack.action.down"), action: "stack.down", icon: "arrow_downward--outlined" },
    ];

    return (
        <div className="page stack-page">
            <div className="page-header stack-page__header">
                <h1 className="type-headline-small">{stackName}</h1>
                {endpoint !== "" ? (
                    <span className="status-chip status-chip--info type-label-medium">{hostLabel}</span>
                ) : null}
                <StatusChip status={STATUS_WORD[summary?.status ?? 0] ?? "unknown"} />

                {sizeClass !== "compact" ? (
                    <div className="page-header__actions stack-page__actions">
                        {editing ? (
                            <>
                                <mdui-button
                                    variant="filled"
                                    disabled={submitting}
                                    loading={submitting}
                                    onClick={() => void deploy()}
                                >
                                    {t("stack.action.deploy")}
                                </mdui-button>
                                <mdui-button
                                    variant="tonal"
                                    disabled={submitting}
                                    onClick={() => void saveDraft()}
                                >
                                    {t("stack.action.save")}
                                </mdui-button>
                                <mdui-button variant="text" disabled={submitting} onClick={discard}>
                                    {t("stack.action.discard")}
                                </mdui-button>
                            </>
                        ) : (
                            <>
                                {stackIsManaged ? (
                                    <mdui-button variant="tonal" onClick={() => setMode("edit")}>
                                        {t("stack.action.edit")}
                                    </mdui-button>
                                ) : null}
                                {viewActions.map((entry) => (
                                    <mdui-button
                                        key={entry.action}
                                        variant="text"
                                        disabled={submitting}
                                        onClick={() => lifecycleMutation.mutate(entry.action)}
                                    >
                                        {entry.label}
                                    </mdui-button>
                                ))}
                                <mdui-button
                                    variant="text"
                                    className="danger-action"
                                    onClick={() => setDeleteConfirm(true)}
                                >
                                    {t("stack.action.delete")}
                                </mdui-button>
                            </>
                        )}
                    </div>
                ) : null}
            </div>

            {hostOffline ? (
                <div className="banner type-body-medium" role="status">
                    <mdui-icon name="cloud_off--outlined" />
                    {t("stack.hostOffline")}
                </div>
            ) : null}

            {stackIsExternal ? (
                <div className="banner banner--info type-body-medium" role="status">
                    <mdui-icon name="info--outlined" />
                    {t("stack.notManaged")}
                </div>
            ) : null}

            {stackIsManaged ? editorPane : null}

            <div className="section">
                {serviceNames.map((name) => (
                    <ServiceCard
                        key={name}
                        name={name}
                        stackName={stackName}
                        service={config.services?.[name]}
                        editable={editing}
                        multiService={serviceNames.length > 1}
                        status={serviceStatus[name]}
                        stats={statsForService(name)}
                        expandedPorts={expandedPortsFor(name)}
                        availableNetworks={availableNetworks}
                        onStart={(service) => serviceMutation.mutate({ action: "service.start", service })}
                        onStop={(service) => serviceMutation.mutate({ action: "service.stop", service })}
                        onRestart={(service) =>
                            serviceMutation.mutate({ action: "service.restart", service })
                        }
                        onRemove={removeService}
                        onServiceChange={applyServicePatch}
                    />
                ))}
            </div>

            <mdui-card>
                <div className="card-title">
                    <h2 className="type-title-medium">{t("stack.terminal.progress")}</h2>
                </div>
                <TerminalView
                    endpoint={endpoint}
                    terminal={composeTerminalName(endpoint, stackName)}
                    interactive={false}
                    rows={8}
                />
            </mdui-card>
            <mdui-card>
                <div className="card-title">
                    <h2 className="type-title-medium">{t("terminal.output")}</h2>
                </div>
                <TerminalView
                    endpoint={endpoint}
                    terminal={logsTerminalName(endpoint, stackName)}
                    interactive={false}
                    rows={20}
                />
            </mdui-card>

            {/*
              Compact carries one primary action plus an overflow sheet, so the thumb zone holds
              the action a user actually came for instead of a row of equal-weight buttons.
            */}
            {sizeClass === "compact" ? (
                <div className="stack-bottom-bar">
                    <mdui-button-icon
                        href="/"
                        icon="arrow_back"
                        aria-label={t("action.back")}
                        onClick={linkHandler("/")}
                    />
                    {editing ? (
                        <mdui-button
                            variant="filled"
                            disabled={submitting}
                            loading={submitting}
                            onClick={() => void deploy()}
                        >
                            {t("stack.action.deploy")}
                        </mdui-button>
                    ) : stackIsExternal ? (
                        <mdui-button variant="filled" onClick={() => setOverflowOpen(true)}>
                            {t("action.actions")}
                        </mdui-button>
                    ) : stackIsManaged ? (
                        <mdui-button variant="filled" onClick={() => setMode("edit")}>
                            {t("stack.action.edit")}
                        </mdui-button>
                    ) : null}
                    {stackIsManaged ? (
                        <mdui-button-icon
                            icon="more_vert"
                            aria-label={t("action.more")}
                            onClick={() => setOverflowOpen(true)}
                        />
                    ) : null}
                </div>
            ) : null}

            <BottomSheet
                open={overflowOpen}
                title={stackName}
                onClose={() => setOverflowOpen(false)}
            >
                <mdui-list>
                    {editing ? (
                        <>
                            <mdui-list-item
                                icon="save--outlined"
                                onClick={() => {
                                    setOverflowOpen(false);
                                    void saveDraft();
                                }}
                            >
                                {t("stack.action.save")}
                            </mdui-list-item>
                            <mdui-list-item
                                icon="undo"
                                onClick={() => {
                                    setOverflowOpen(false);
                                    discard();
                                }}
                            >
                                {t("stack.action.discard")}
                            </mdui-list-item>
                        </>
                    ) : (
                        viewActions.map((entry) => (
                            <mdui-list-item
                                key={entry.action}
                                icon={entry.icon}
                                disabled={submitting}
                                onClick={() => {
                                    setOverflowOpen(false);
                                    lifecycleMutation.mutate(entry.action);
                                }}
                            >
                                {entry.label}
                            </mdui-list-item>
                        ))
                    )}
                    <mdui-list-item
                        icon="delete--outlined"
                        className="danger-text"
                        onClick={() => {
                            setOverflowOpen(false);
                            setDeleteConfirm(true);
                        }}
                    >
                        {t("stack.action.delete")}
                    </mdui-list-item>
                </mdui-list>
            </BottomSheet>

            <ConfirmDialog
                open={deleteConfirm}
                danger
                title={t("stack.action.delete")}
                message={t("stack.action.deleteConfirm", { name: stackName })}
                confirmLabel={t("stack.action.delete")}
                onConfirm={() => {
                    setDeleteConfirm(false);
                    lifecycleMutation.mutate("stack.delete", {
                        onSuccess: () => void navigate("/"),
                    });
                }}
                onCancel={() => setDeleteConfirm(false)}
            />
        </div>
    );
}
